a = "henry".capitalize()
print(a)
b = "Charles".center(20, "x")
print(b)
c = "Si Pancha plancha con cuatro planchas, ¿con cuantas planchas Pancha plancha?".count("a")
print(c)
d = "charles henry".encode("utf-8")
print(d)
e = "final".endswith("a")
print(e)
f = "Murcielago".find("a")
print(f)
g = "Me llamo {} y estoy aprendiendo Python".format("Charles Henry")
print(g)
h = "Cristinet".index("n")
print(h)
i = "acm1pt".isalnum()
print(i)
j = "kkck".isalpha()
print(j)
k = "3443".isdecimal()
print(k)
l = "6971".isdigit()
print(l)
m = "probando".islower()
print(m)
n = "6669".isnumeric()
print(n)
o = "se puede imprimir?".isprintable()
print(o)
p = " ".isspace()
print(p)
r = "Todas Las Palabras Empiezan Con Mayusculas".istitle()
print(r)
s = "MAYUS".isupper()
print(s)
t = "o".join(["s","n ","ch", " l", "s m","n","s"])
print(t)
u = "GRITANDO!".lower()
print(u)
v = "hamburguesa".replace("hamburgu", "milan")
print(v)
w = "s.e.p.a.r.a.n.d.o".split(".")
print(w)
x = "Socorro!!".startswith("S")
print(x)
y = "  34   43     ".strip()
print(y)
z = "esto quiero que sea un titulo ok?".title()
print(z)
A = "no me calmo nada entendes!!!".upper()
print(A)
B = " llename de ceros papasito siiii".zfill(50)
print(B)
C = "                    quitando espacios de la izquiera".lstrip()
print(C)
D = "ahora quito los de la derecha                           ".rstrip()
print(D)
E = "Charles Henry".ljust(25)
print(E)
F = "Meza Eichenberger".rjust(25)
print(F)

