
a = "PyThon".istitle()
print(a, "1")
b = "Este Es Un Titulo".istitle()
print(b, "2")
c = "Este es un Titulo".istitle()
print(c,"3")
d = "Python".istitle()
print(d,"4")
e = "Este es un titulo".istitle()
print(e, "5")
f = "7 Cajas".istitle()
print(f, "6")
g = "abracadabra".replace("a", "e")
print(g)
h = "        python es genial!   ".strip()
print(h)
i = "1, 2, 3, 4".split(", ")
print(i)
j = "3!".isupper()
print(j)
k = "Python".isupper()
print(k)
l = "PYTHON3!".isupper()
print(l)
m = "PYTHON".isupper()
print(m)
print('\'Hola \n Mundo!\'')
n = "python".endswith("on".swapcase())
print(n)
o = "Presiona el boton ON".endswith("on".swapcase())
print(o)
p = "PYTHON".endswith("on".swapcase())
print(p)
q = "PYTHON es un buen lenguaje".endswith("on".swapcase())
print(q)
r = "Python".endswith("on".swapcase())
print(r)
a_list = ["1","2","3"]
A = "-".join(a_list)
print(A)
#B = '{}{}{}'.format(a_list)
#print(B)
#C = a_list.join('-')
#print(C)
#D = join(a_list, "-")